{"name": "Try to update pet with invalid parameter", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200", "trace": "self = <tests_project.tests.test_update_pet.TestUpdatePet object at 0x7f8321c625f0>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Try to update pet with invalid parameter\")\n    def test_update_pet_with_invalid_parameter(self):\n        pet = self.create_pet()\n        pet_id = self.get_json_value(pet, \"id\")\n        data = {\n            \"id\": pet_id,\n            \"name\": self.fake.first_name(),\n            \"owner\": self.fake.name()\n        }\n    \n        response = MyRequests.put(\n            \"/pet/\",\n            data)\n    \n>       Assertions.assert_code_status(response, 405)\n\ntests/test_update_pet.py:182: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, expected_status_code = 405\n\n    @staticmethod\n    @allure.step(\"Check status code is {expected_status_code}\")\n    def assert_code_status(response: Response, expected_status_code):\n>       assert response.status_code == expected_status_code, \\\n            f\"Unexpected status code! Expected: {expected_status_code}. Actual: {response.status_code}\"\nE       AssertionError: Unexpected status code! Expected: 405. Actual: 200\n\nlib/assertions.py:30: AssertionError"}, "steps": [{"name": "Create pet", "status": "passed", "steps": [{"name": "Prepare pet creation data", "status": "passed", "start": 1744662021319, "stop": 1744662021319}, {"name": "POST request to URL '/pet/'", "status": "passed", "start": 1744662021319, "stop": 1744662021327}], "start": 1744662021318, "stop": 1744662021327}, {"name": "PUT request to URL '/pet/'", "status": "passed", "start": 1744662021327, "stop": 1744662021335}, {"name": "Check status code is 405", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200\n", "trace": "  File \"/usr/local/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/tests_project/lib/assertions.py\", line 30, in assert_code_status\n    assert response.status_code == expected_status_code, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_status_code", "value": "405"}], "start": 1744662021335, "stop": 1744662021335}], "start": 1744662021318, "stop": 1744662021336, "uuid": "5404a572-f562-4d7e-96e1-d3ad05f2f5eb", "historyId": "adc48696744505bc8d84da93ee446799", "testCaseId": "adc48696744505bc8d84da93ee446799", "fullName": "tests.test_update_pet.TestUpdatePet#test_update_pet_with_invalid_parameter", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_pet"}, {"name": "subSuite", "value": "TestUpdatePet"}, {"name": "host", "value": "4c2631702ffc"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_pet"}]}