{"name": "Find pets by incorrect status", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`\"}' instead of Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`", "trace": "self = <tests.test_find_by_status.TestFindByStatus object at 0x1062c44c0>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.title(\"Find pets by incorrect status\")\n    def test_find_pets_by_incorrect_status(self):\n        incorrect_status = \"free\"\n        response = MyRequests.get(\n            f\"/pet/findByStatus?status={incorrect_status}\")\n    \n        Assertions.assert_code_status(response, 400)\n>       Assertions.assert_error_message(\n            response, f\"Input error: query parameter `status value `{incorrect_status}` is not in the allowable values `[available, pending, sold]`\")\n\ntests/test_find_by_status.py:75: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [400]>, expected_error_message = 'Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`'\n\n    @staticmethod\n    @allure.step(\"Check the server returns error message '{expected_error_message}'\")\n    def assert_error_message(response: Response, expected_error_message):\n>       assert response.content.decode() == expected_error_message, \\\n            f\"Unexpected error message: {response.content} instead of {expected_error_message}\"\nE       AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`\"}' instead of Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`\n\nlib/assertions.py:46: AssertionError"}, "steps": [{"name": "GET request to URL '/pet/findByStatus?status=free'", "status": "passed", "start": 1744657923193, "stop": 1744657923200}, {"name": "Check status code is 400", "status": "passed", "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_status_code", "value": "400"}], "start": 1744657923201, "stop": 1744657923201}, {"name": "Check the server returns error message ''Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`''", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: b'{\"code\":400,\"message\":\"Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`\"}' instead of Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`\n", "trace": "  File \"/Users/miowch/.pyenv/versions/n26_nastia_kuzina/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/Users/miowch/Documents/GitHub/nastia-kuzina/Task3/api-e2e-tests/lib/assertions.py\", line 46, in assert_error_message\n    assert response.content.decode() == expected_error_message, \\\n"}, "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "expected_error_message", "value": "'Input error: query parameter `status value `free` is not in the allowable values `[available, pending, sold]`'"}], "start": 1744657923201, "stop": 1744657923201}], "start": 1744657923193, "stop": 1744657923201, "uuid": "5aca31c4-b2d5-4e5e-8bfb-ee4e97303574", "historyId": "fbe0265c58a3833e7af6eea29943d36e", "testCaseId": "fbe0265c58a3833e7af6eea29943d36e", "fullName": "tests.test_find_by_status.TestFindByStatus#test_find_pets_by_incorrect_status", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_find_by_status"}, {"name": "subSuite", "value": "TestFindByStatus"}, {"name": "host", "value": "iMac.local"}, {"name": "thread", "value": "58784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_find_by_status"}]}