{"name": "Try to create pet with invalid parameter", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200", "trace": "self = <tests.test_add_pet.TestAddPet object at 0x106232c50>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Try to create pet with invalid parameter\")\n    def test_add_pet_with_invalid_parameter(self):\n        data = {\n            \"id\": random.randint(1, 1000),\n            \"name\": self.fake.first_name(),\n            \"owner\": self.fake.name()\n        }\n    \n        response = MyRequests.post(\n            \"/pet/\",\n            data)\n    \n>       Assertions.assert_code_status(response, 405)\n\ntests/test_add_pet.py:225: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, expected_status_code = 405\n\n    @staticmethod\n    @allure.step(\"Check status code is {expected_status_code}\")\n    def assert_code_status(response: Response, expected_status_code):\n>       assert response.status_code == expected_status_code, \\\n            f\"Unexpected status code! Expected: {expected_status_code}. Actual: {response.status_code}\"\nE       AssertionError: Unexpected status code! Expected: 405. Actual: 200\n\nlib/assertions.py:30: AssertionError"}, "steps": [{"name": "POST request to URL '/pet/'", "status": "passed", "start": 1744657923047, "stop": 1744657923054}, {"name": "Check status code is 405", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status code! Expected: 405. Actual: 200\n", "trace": "  File \"/Users/miowch/.pyenv/versions/n26_nastia_kuzina/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/Users/miowch/Documents/GitHub/nastia-kuzina/Task3/api-e2e-tests/lib/assertions.py\", line 30, in assert_code_status\n    assert response.status_code == expected_status_code, \\\n"}, "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_status_code", "value": "405"}], "start": 1744657923055, "stop": 1744657923055}], "start": 1744657923047, "stop": 1744657923055, "uuid": "fd0a30b4-e1fd-4384-9e8a-8ad581ac1dec", "historyId": "627991423627d15444edf0fd4336b824", "testCaseId": "627991423627d15444edf0fd4336b824", "fullName": "tests.test_add_pet.TestAddPet#test_add_pet_with_invalid_parameter", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_add_pet"}, {"name": "subSuite", "value": "TestAddPet"}, {"name": "host", "value": "iMac.local"}, {"name": "thread", "value": "58784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_add_pet"}]}